name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [i686-pc-windows-gnu]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.toolchain }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.toolchain }}
      - name: clippy warnings
        run: cargo +${{ matrix.toolchain }} clippy -- -D warnings -A dead_code

  code_style:
    name: Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: fmt
        run: cargo fmt --check