name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable-i686-pc-windows-gnu]
    steps:
      - uses: actions/checkout@v3
      - name: install toolchain
        run: rustup target add ${{ matrix.toolchain }}
      - name: clippy warnings
        run: cargo +${{ matrix.toolchain }} clippy -- -D warnings -A dead_code
      - name: build
        run: cargo build --target=${{ matrix.toolchain }}

  code_style:
    name: Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: fmt
        run: cargo fmt --check