name: Build

on: [push]

jobs:
  build_windows:
    name: Windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: i686-pc-windows-gnu
          override: true
      - name: clippy warnings
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: clippy
          args: -- -D warnings -A dead_code
      - name: build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target i686-pc-windows-gnu

  code_style:
    name: Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: fmt
        run: cargo fmt --check